### ISSUE TITLE
Design security architecture

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#127]
A space to discuss Coral's approach to Auth.

**Comment by ardan-bkennedy** [comment]
Authentication/Authorization:

- Build the ability to allow users to authenticate into Anvil from all our front ends.
- Anvil will manage users whether the user is a proxy from another system or owned exclusively by Anvil.
- A user must authenticate into Anvil for every application we have in Coral before using Xenia and Pillar.
- Once a user authenticates, Anvil provides a token to be used for API access in Pillar and Xenia.
- When Xenia or Pillar receives a request, it extracts JSON web token from the header.

_**Christian**: Tokens will be handled according to RFC 6750: OAuth 2.0 Bearer Token Usage. This is very similar to HTTP Basic Auth, but uses a different scheme._

- Using the Anvil public key, the token in decrypted.

_**Christian**: Tokens are JSON Web Tokens (JWT) signed by Anvil using it's private key. The corresponding public key is available in the form of a JSON Web Key at an endpoint your apps/APIs can request when starting up. You can use this key to verify the token's signatures._

- Inside the decrypted token an Anvil UserId and a set of authorization keys is provided.
- These authorization keys are mapped to a product specific set of authorization roles know by Xenia and Pillar respectively.

_**Christian**: The payload of each token includes a number of attributes that can be used for further verification, such as the issuer, expiration, user's id, permissions (in the form of OAuth 2.0 scopes) and so on. Anvil supports Role-based Access Control on the server side (Anvil) to determine which users (and clients) can be issued tokens with any given scope._

- Xenia and Pillar are responsible for making sure these roles are implemented.
- Xenia and Pillar never need to talk with Anvil again after receiving the Public Key.

_**Christian**: Coral services will request Anvil Connect's public key(s) in order to verify token signatures. This will happen once when the service first boots. Once the service has the public key, it can authenticate tokens without making a round trip request to Anvil._

_**Christian**: This type of authentication (verifying signatures) is quite strong thanks to cryptography. The drawback is that using this method alone it's not possible to determine if a token has been revoked. For many cases, assuming your token expirations are reasonable, this doesn't present a serious problem. If it is a hard requirement to verify the token has not been revoked with each request, you can also (or alternatively) send the the token to your Anvil instance to verify._

User Management:
- Cay will provide a front end to add users to Anvil or configure authorization rules.
- If Anvil is setup with an integration, the act of logging in may create the Anvil user.

_**Christian**: This is correct. Signing in for the first time with any "provider" such as Facebook, or an LDAP or SAML server, creates a user record in Anvil._

- Once an Anvil user exists, we need an admin role to configure the authorization rules.
- We may need to add new authorization rules as well.

_**Christian**: When you first deploy the auth server and run "$ nvl setup" (nvl is our CLI admin tool), an authority (admin) user will be created. Once you have this user, you can manage many aspects of the server via nvl._

_**Christian**: Depending on your specific requirements, we may be able to automate role assignment in some cases, e.g., having users assigned certain roles by default when signing up._

From a Xenia and Pillar perspective, it knows nothing about Anvil outside of the Public key it needs to perform the decryption. Everything in terms of authorization for this user is inside the JSON web token plus the UserId, which is fantastic because this information is never accessible over the wire directly.

My next steps is to map all the things in Xenia that need authorization around it. Then try to identify the smallest set of authorization roles possible to give us the best level of authorization we can achieve. I will create this mapping of authorization roles to feature/functionality.

**Some additional background from Christian:**

Anvil Connect is an open source implementation of OpenID Connect. We support the Core, Discovery, Dynamic Client Registration, and Session Management (SSO) specs. 

OpenID Connect itself is a profile of OAuth 2.0, and incorporates other standards such as JSON Web Tokens and JSON Web Signatures. 

We've attempted to stay as close to these specs as possible to be fully interoperable. For the most part, compliant client libraries for any number of languages and frameworks should work out of the box.

For anyone working directly on integrating apps and APIs with Anvil, it's helpful (but not entirely necessary) to have to have a cursory understanding of these protocols. We maintain a list of references in the GitHub wiki. Documentation for Anvil Connect is in a separate repository.

**Comment by ardan-bkennedy** [comment]
I think this has been figured out and new issues are being created.
